services:
  - type: web
    name: edge-metrics-ojt
    env: python
    plan: free
    region: singapore
    buildCommand: ""
    startCommand: "python exporter.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
